New Console App
aliencube/youtube-subtitles-extractor pull request #12
Opened 2023-10-17 18:33 UTC by mvillajos

Added new console project to test use case

2023-11-08 09:06 UTC, justinyoo requested changes
@mvillajos Thanks for your PR! However, I'd like you to take a look at the "proper" way of building a console app.

2023-11-08 09:06 UTC, justinyoo commented on consoleApp/YouTubeSubtitlesExtractorConsoleApp/Program.cs
Use the generic builder pattern like:

```csharp
var host = Host.CreateDefaultBuilder(args);
...
```

Please refer to: https://learn.microsoft.com/dotnet/core/extensions/generic-host

2023-11-09 12:20 UTC, mvillajos commented
I´ll take a review of my code and install .Net 8

2025-04-12 10:52 UTC, justinyoo commented
@mvillajos Thanks for your PR. It's merged through #14

2025-04-12 10:52 UTC, closed without merging